### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by ithotline3** [daniabib/csgo-aimbot#1]
Tried to run this one and got this error, could you give some hint how to fix it?

Traceback (most recent call last):
  File "aim-bot.py", line 39, in <module>
    def get_targets(results: list, labels: list[int]) -> list[Target]:
TypeError: 'type' object is not subscriptable

Looking at the line 39, I saw this:

def get_targets(results: list, labels: list[int]) -> list[Target]:
    """Returns a list with results filtered by the classes specified in the labels argument."""
    return [Target(target) for target in results.xywh[0] if target[5] in labels]

**Comment by daniabib** [comment]
You're probably trying to run it with an older python version. The syntax for type annotation was changed in Python 3.9, and I used it in the code, like in line 39:

```
def get_targets(results: list, labels: list[int]) -> list[Target]:
```

Try to install Python 3.9 or greater and that should work.

If you don't want to change your system's default python you can use something like [pyenv](https://github.com/pyenv/pyenv) to install different versions of python.

I will add the python version required to run it in the README.

Thank you.

**Comment by ithotline3** [comment]
Ah I see, thanks for the info. Indeed I'm running python 3.8.
