### ISSUE TITLE
.

### ISSUE THREAD

**Issue by gtr667gwy45** [daniabib/csgo-aimbot#3]
.

**Comment by gtr667gwy45** [comment]
@daniabib hi please would you mind kindly share csgo dataset images and labels for this project? please thank you very much i really appreciate it

**Comment by gtr667gwy45** [comment]
@daniabib  please kindly share csgo datasets, thank you

**Comment by daniabib** [comment]
Hi! Apologies for the delay. Sorry, I don't have access to it anymore.
